# Goals:
Filter the Orphanet complete file to only include:
 - Rows with >=1 stat AND 1 or less GARD IDs

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Orphanet-Comparison-FINAL.csv')
df

,OrphaCode,Disease Name,Orpha Epi Type,Orpha Epi Class,Orpha Epi Rate,Orpha Loc,PMID,Title+Abstract,GARD Disease ID,Pipeline Disease,Epi Identifier,Epi Statistics,Model Location,Model Date,Model Sex,Model Ethnicity
0,166024,"Multiple epiphyseal dysplasia, Al-Gazali type",Point prevalence,<1 / 1 000 000,0.00,Worldwide,11389160,Localisation of a gene for an autosomal recess...,[],[],set(),[],{'worldwide'},set(),set(),{'oman'}
1,166024,"Multiple epiphyseal dysplasia, Al-Gazali type",Point prevalence,<1 / 1 000 000,0.00,Worldwide,9689990,"Autosomal recessive syndrome of macrocephaly, ...",[],[],set(),[],{'worldwide'},set(),set(),{'oman'}
2,166032,"Multiple epiphyseal dysplasia, with miniepiphyses",Point prevalence,<1 / 1 000 000,0.00,Worldwide,15523498,Mutations in the known genes are not the major...,[],[],set(),[],{'worldwide'},set(),set(),set()
3,61,Alpha-mannosidosis,Prevalence at birth,<1 / 1 000 000,0.09,Australia,9918480,Prevalence of lysosomal storage disorders. <h4...,[],[],"{'combined prevalence', 'prevalence'}","['1 per 57000 live births', '1 per 4 . 2 milli...","{'australia', '##tralia', 'aus'}","{'ja', 'december 31 , 1996', '##nuary 1 , 1980...",set(),"{'##tralian', 'aus'}"
4,61,Alpha-mannosidosis,Prevalence at birth,1-9 / 1 000 000,0.13,Norway,7900112,[Alpha-mannosidosis]. Alpha-mannosidosis is a ...,[],[],set(),[],"{'##so', 'trom'}",{'between 1983 and 1987'},set(),set()
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6377,99812,LIG4 syndrome,Point prevalence,<1 / 1 000 000,0.00,Worldwide,27717373,DNA ligase IV syndrome; a review. DNA ligase I...,[],[],set(),[],{'worldwide'},set(),set(),set()
6378,99806,Oculootodental syndrome,Point prevalence,<1 / 1 000 000,0.00,Worldwide,12147582,First genomic localization of oculo-oto-dental...,[],[],set(),[],{'worldwide'},set(),set(),"{'br', '##itis'}"
6379,99807,PEHO-like syndrome,Point prevalence,<1 / 1 000 000,0.00,Worldwide,15968934,"Progressive encephalopathy with edema, hypsarr...",['GARD:0010559'],['child'],set(),[],{'worldwide'},set(),set(),set()
6380,99792,Dentin dysplasia-sclerotic bones syndrome,Point prevalence,<1 / 1 000 000,0.00,Worldwide,264650,Dentine dysplasia with sclerotic bone and skel...,[],[],set(),[],{'worldwide'},set(),set(),set()
6381,99776,Mosaic trisomy 9,Point prevalence,<1 / 1 000 000,0.00,Worldwide,22249800,New report of two patients with mosaic trisomy...,['GARD:0000043'],['mosaic trisomy 9'],set(),[],{'worldwide'},set(),"{'boy', 'girl'}",set()

In [3]:
#converts string sets or lists into a python list
def str2list(string,isRate):
    if isRate:
        if string =='[]':
            #removes all stats with empty lists (list of len 0)
            return np.NaN
        else:
            string = str(string).replace("['","")
            string = string.replace("']","")
            string = str(string).replace("{'","")
            string = string.replace("'}","")
            string = string.strip()
            str_list = string.split("', '")
            return str_list
    else:
        string = str(string).replace("['","")
        string = string.replace("']","")
        string = str(string).replace("{'","")
        string = string.replace("'}","")
        string = string.strip()
        str_list = string.split("', '")
        if len(str_list)>1:
            return np.NaN
        else: 
            return str_list

In [4]:
for i in range(len(df['GARD Disease ID'])):
    df['GARD Disease ID'][i] = str2list(df['GARD Disease ID'][i],False)
    df['Epi Statistics'][i] = str2list(df['Epi Statistics'][i],True)

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [5]:
df['GARD Disease ID']

0                 [[]]
1                 [[]]
2                 [[]]
3                 [[]]
4                 [[]]
             ...
6377              [[]]
6378              [[]]
6379    [GARD:0010559]
6380              [[]]
6381    [GARD:0000043]
Name: GARD Disease ID, Length: 6382, dtype: object

In [6]:
df

,OrphaCode,Disease Name,Orpha Epi Type,Orpha Epi Class,Orpha Epi Rate,Orpha Loc,PMID,Title+Abstract,GARD Disease ID,Pipeline Disease,Epi Identifier,Epi Statistics,Model Location,Model Date,Model Sex,Model Ethnicity
0,166024,"Multiple epiphyseal dysplasia, Al-Gazali type",Point prevalence,<1 / 1 000 000,0.00,Worldwide,11389160,Localisation of a gene for an autosomal recess...,[[]],[],set(),NaN,{'worldwide'},set(),set(),{'oman'}
1,166024,"Multiple epiphyseal dysplasia, Al-Gazali type",Point prevalence,<1 / 1 000 000,0.00,Worldwide,9689990,"Autosomal recessive syndrome of macrocephaly, ...",[[]],[],set(),NaN,{'worldwide'},set(),set(),{'oman'}
2,166032,"Multiple epiphyseal dysplasia, with miniepiphyses",Point prevalence,<1 / 1 000 000,0.00,Worldwide,15523498,Mutations in the known genes are not the major...,[[]],[],set(),NaN,{'worldwide'},set(),set(),set()
3,61,Alpha-mannosidosis,Prevalence at birth,<1 / 1 000 000,0.09,Australia,9918480,Prevalence of lysosomal storage disorders. <h4...,[[]],[],"{'combined prevalence', 'prevalence'}","[1 per 57000 live births, 1 per 4 . 2 million ...","{'australia', '##tralia', 'aus'}","{'ja', 'december 31 , 1996', '##nuary 1 , 1980...",set(),"{'##tralian', 'aus'}"
4,61,Alpha-mannosidosis,Prevalence at birth,1-9 / 1 000 000,0.13,Norway,7900112,[Alpha-mannosidosis]. Alpha-mannosidosis is a ...,[[]],[],set(),NaN,"{'##so', 'trom'}",{'between 1983 and 1987'},set(),set()
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6377,99812,LIG4 syndrome,Point prevalence,<1 / 1 000 000,0.00,Worldwide,27717373,DNA ligase IV syndrome; a review. DNA ligase I...,[[]],[],set(),NaN,{'worldwide'},set(),set(),set()
6378,99806,Oculootodental syndrome,Point prevalence,<1 / 1 000 000,0.00,Worldwide,12147582,First genomic localization of oculo-oto-dental...,[[]],[],set(),NaN,{'worldwide'},set(),set(),"{'br', '##itis'}"
6379,99807,PEHO-like syndrome,Point prevalence,<1 / 1 000 000,0.00,Worldwide,15968934,"Progressive encephalopathy with edema, hypsarr...",[GARD:0010559],['child'],set(),NaN,{'worldwide'},set(),set(),set()
6380,99792,Dentin dysplasia-sclerotic bones syndrome,Point prevalence,<1 / 1 000 000,0.00,Worldwide,264650,Dentine dysplasia with sclerotic bone and skel...,[[]],[],set(),NaN,{'worldwide'},set(),set(),set()
6381,99776,Mosaic trisomy 9,Point prevalence,<1 / 1 000 000,0.00,Worldwide,22249800,New report of two patients with mosaic trisomy...,[GARD:0000043],['mosaic trisomy 9'],set(),NaN,{'worldwide'},set(),"{'boy', 'girl'}",set()

In [7]:
df.dropna()

,OrphaCode,Disease Name,Orpha Epi Type,Orpha Epi Class,Orpha Epi Rate,Orpha Loc,PMID,Title+Abstract,GARD Disease ID,Pipeline Disease,Epi Identifier,Epi Statistics,Model Location,Model Date,Model Sex,Model Ethnicity
3,61,Alpha-mannosidosis,Prevalence at birth,<1 / 1 000 000,0.09,Australia,9918480,Prevalence of lysosomal storage disorders. <h4...,[[]],[],"{'combined prevalence', 'prevalence'}","[1 per 57000 live births, 1 per 4 . 2 million ...","{'australia', '##tralia', 'aus'}","{'ja', 'december 31 , 1996', '##nuary 1 , 1980...",set(),"{'##tralian', 'aus'}"
5,61,Alpha-mannosidosis,Prevalence at birth,<1 / 1 000 000,0.09,Netherlands,10480370,The frequency of lysosomal storage diseases in...,[[]],[],"{'birth prevalences', 'combined birth prevalen...","[14 per 100 , 000 live births, 2 . 0 per 100 ,...",{'netherlands'},"{'1970 - 1996', 'between 1970 and 1996'}",set(),set()
6,61,Alpha-mannosidosis,Prevalence at birth,1-9 / 1 000 000,0.12,Portugal,14685153,Prevalence of lysosomal storage diseases in Po...,[[]],[],"{'overall birth prevalence', 'prevalence'}","[25 / 100000 live births, than, 0 . 5 / 100000...","{'australia', '##ian', 'netherlands'}",set(),set(),"{'##ues', '##uga', 'du', 'port', 'aus', '##tch..."
7,61,Alpha-mannosidosis,Prevalence at birth,1-9 / 1 000 000,0.38,Czech Republic,20490927,The birth prevalence of lysosomal storage diso...,[[]],[],"{'birth prevalence', 'overall prevalence', 'pr...","[12 . 25 per 100 , 000, 14 per 100 , 000, 12 ....","{'the czech republic', 'italy', 'australia', '...",{'between 1975 and 2008'},set(),{'cz'}
8,61,Alpha-mannosidosis,Prevalence at birth,<1 / 1 000 000,0.07,Sweden,25274184,Epidemiology of lysosomal storage diseases in ...,[[]],[],"{'incidence', 'collective incidence', 'total'}","[one in every 6100 births, one in 39 000, one ...","{'salla', '##ede', 'sw', 'of', 'northern swede...",{'1980 - 2009'},set(),{'sw'}
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6366,99880,Hyperparathyroidism-jaw tumor syndrome,Point prevalence,<1 / 1 000 000,0.00,Worldwide,25511968,Tumor suppressor gene mutation in a patient wi...,[[]],[],"{'incidence', 'prevalence'}",[unknown],{'worldwide'},"{'1958', '1990'}","{'male', 'female'}",set()
6367,99885,Isolated permanent neonatal diabetes mellitus,Prevalence at birth,1-9 / 1 000 000,0.46,Slovakia,17213273,Prevalence of permanent neonatal diabetes in S...,[[]],[],"{'incidence', 'prevalence', 'frequency'}","[one case in 215 , 417 live births, one in 215...","{'s', 'su', '##lovakia'}",{'1981'},set(),set()
6368,99885,Isolated permanent neonatal diabetes mellitus,Prevalence at birth,1-9 / 1 000 000,0.40,United States,23050777,Permanent neonatal diabetes mellitus: prevalen...,[[]],[],"{'population prevalence', 'prevalence'}",[1 in 252 000],{'us'},{'2001 - 2008'},set(),set()
6369,99885,Isolated permanent neonatal diabetes mellitus,Prevalence at birth,1-5 / 10 000,18.00,Oman,10798084,Permanent neonatal diabetes mellitus: epidemio...,[[]],[],"{'incidence', 'prevalence rates', 'prevalence ...","[1 . 788 + / - 0 . 82 per 100 , 000 live birth...","{'sultanate of', 'oman'}","{'end of december 1994', 'january 1989 to dece...",set(),set()
6374,99853,Ovarioleukodystrophy,Point prevalence,<1 / 1 000 000,0.00,Worldwide,12707859,Ovarian failure related to eukaryotic initiati...,[[]],[],{'occurs'},[1 %],{'worldwide'},set(),{'women'},set()

In [8]:
df.dropna().to_csv('Orphanet-Comparison-FINAL-FILTERED.csv', header = True, index=False, encoding='utf-8')